steps:

- name: 'gcr.io/cloud-builders/docker'

  args: ["build", "-t", "gcr.io/$PROJECT_ID/nginx-asd:v1.0", "."]

- name: 'gcr.io/cloud-builders/docker'

  args: ["push", "gcr.io/$PROJECT_ID/nginx-asd:v1.0"]

- name: 'gcr.io/cloud-builders/kubectl'

  args:

  - 'set'

  - '--namespace'

  - 'default'

  - 'image'

  - 'deployment/nginx-1'

  - 'nginx=gcr.io/$PROJECT_ID/nginx-asd:v1.0'

  env:

  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'

  - 'CLOUDSDK_CONTAINER_CLUSTER=kb-dev-cluster'

images: ['gcr.io/$PROJECT_ID/nginx-asd:v1.0']
